//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStorageSetting
    {
        public int Id { get; set; }
        public string StorageUrl { get; set; }
        public string StorageLocalFolder { get; set; }
        public string StoragePath { get; set; }
        public string FullPath { get; set; }
    }
}
