//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RijndaelAESEncryptionHistory
    {
        public int Id { get; set; }
        public string SourcePhrase { get; set; }
        public string EncryptedPhrase { get; set; }
        public int PhraseEncryptionRequestsCount { get; set; }
        public byte[] EncryptionVectorUsed { get; set; }
        public byte[] EncryptionKeyUsed { get; set; }
    }
}
